on:
  workflow_dispatch:

permissions:
  id-token: write

name: Run Azure Login With a Service Principal Secret
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
